/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as authRedirToDashboardRouteRouteImport } from './routes/(auth)/_redir-to-dashboard/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authRedirToDashboardSignupRouteImport } from './routes/(auth)/_redir-to-dashboard/signup'
import { Route as authRedirToDashboardLoginRouteImport } from './routes/(auth)/_redir-to-dashboard/login'
import { Route as authRedirToDashboardInvalidResetTokenRouteImport } from './routes/(auth)/_redir-to-dashboard/invalid-reset-token'
import { Route as authRedirToDashboardForgotPasswordRouteImport } from './routes/(auth)/_redir-to-dashboard/forgot-password'
import { Route as authRedirToDashboardExpiredResetTokenRouteImport } from './routes/(auth)/_redir-to-dashboard/expired-reset-token'
import { Route as authRedirToDashboardResetPasswordTokenRouteImport } from './routes/(auth)/_redir-to-dashboard/reset-password.$token'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const authRedirToDashboardRouteRoute =
  authRedirToDashboardRouteRouteImport.update({
    id: '/(auth)/_redir-to-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authRedirToDashboardSignupRoute =
  authRedirToDashboardSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => authRedirToDashboardRouteRoute,
  } as any)
const authRedirToDashboardLoginRoute =
  authRedirToDashboardLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => authRedirToDashboardRouteRoute,
  } as any)
const authRedirToDashboardInvalidResetTokenRoute =
  authRedirToDashboardInvalidResetTokenRouteImport.update({
    id: '/invalid-reset-token',
    path: '/invalid-reset-token',
    getParentRoute: () => authRedirToDashboardRouteRoute,
  } as any)
const authRedirToDashboardForgotPasswordRoute =
  authRedirToDashboardForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authRedirToDashboardRouteRoute,
  } as any)
const authRedirToDashboardExpiredResetTokenRoute =
  authRedirToDashboardExpiredResetTokenRouteImport.update({
    id: '/expired-reset-token',
    path: '/expired-reset-token',
    getParentRoute: () => authRedirToDashboardRouteRoute,
  } as any)
const authRedirToDashboardResetPasswordTokenRoute =
  authRedirToDashboardResetPasswordTokenRouteImport.update({
    id: '/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => authRedirToDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/expired-reset-token': typeof authRedirToDashboardExpiredResetTokenRoute
  '/forgot-password': typeof authRedirToDashboardForgotPasswordRoute
  '/invalid-reset-token': typeof authRedirToDashboardInvalidResetTokenRoute
  '/login': typeof authRedirToDashboardLoginRoute
  '/signup': typeof authRedirToDashboardSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reset-password/$token': typeof authRedirToDashboardResetPasswordTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/expired-reset-token': typeof authRedirToDashboardExpiredResetTokenRoute
  '/forgot-password': typeof authRedirToDashboardForgotPasswordRoute
  '/invalid-reset-token': typeof authRedirToDashboardInvalidResetTokenRoute
  '/login': typeof authRedirToDashboardLoginRoute
  '/signup': typeof authRedirToDashboardSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reset-password/$token': typeof authRedirToDashboardResetPasswordTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/(auth)/_redir-to-dashboard': typeof authRedirToDashboardRouteRouteWithChildren
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/(auth)/_redir-to-dashboard/expired-reset-token': typeof authRedirToDashboardExpiredResetTokenRoute
  '/(auth)/_redir-to-dashboard/forgot-password': typeof authRedirToDashboardForgotPasswordRoute
  '/(auth)/_redir-to-dashboard/invalid-reset-token': typeof authRedirToDashboardInvalidResetTokenRoute
  '/(auth)/_redir-to-dashboard/login': typeof authRedirToDashboardLoginRoute
  '/(auth)/_redir-to-dashboard/signup': typeof authRedirToDashboardSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth)/_redir-to-dashboard/reset-password/$token': typeof authRedirToDashboardResetPasswordTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/expired-reset-token'
    | '/forgot-password'
    | '/invalid-reset-token'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/reset-password/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/expired-reset-token'
    | '/forgot-password'
    | '/invalid-reset-token'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/reset-password/$token'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/(auth)/_redir-to-dashboard'
    | '/_authed/account'
    | '/_authed/dashboard'
    | '/(auth)/_redir-to-dashboard/expired-reset-token'
    | '/(auth)/_redir-to-dashboard/forgot-password'
    | '/(auth)/_redir-to-dashboard/invalid-reset-token'
    | '/(auth)/_redir-to-dashboard/login'
    | '/(auth)/_redir-to-dashboard/signup'
    | '/api/auth/$'
    | '/(auth)/_redir-to-dashboard/reset-password/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  authRedirToDashboardRouteRoute: typeof authRedirToDashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/(auth)/_redir-to-dashboard': {
      id: '/(auth)/_redir-to-dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRedirToDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_redir-to-dashboard/signup': {
      id: '/(auth)/_redir-to-dashboard/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authRedirToDashboardSignupRouteImport
      parentRoute: typeof authRedirToDashboardRouteRoute
    }
    '/(auth)/_redir-to-dashboard/login': {
      id: '/(auth)/_redir-to-dashboard/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authRedirToDashboardLoginRouteImport
      parentRoute: typeof authRedirToDashboardRouteRoute
    }
    '/(auth)/_redir-to-dashboard/invalid-reset-token': {
      id: '/(auth)/_redir-to-dashboard/invalid-reset-token'
      path: '/invalid-reset-token'
      fullPath: '/invalid-reset-token'
      preLoaderRoute: typeof authRedirToDashboardInvalidResetTokenRouteImport
      parentRoute: typeof authRedirToDashboardRouteRoute
    }
    '/(auth)/_redir-to-dashboard/forgot-password': {
      id: '/(auth)/_redir-to-dashboard/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authRedirToDashboardForgotPasswordRouteImport
      parentRoute: typeof authRedirToDashboardRouteRoute
    }
    '/(auth)/_redir-to-dashboard/expired-reset-token': {
      id: '/(auth)/_redir-to-dashboard/expired-reset-token'
      path: '/expired-reset-token'
      fullPath: '/expired-reset-token'
      preLoaderRoute: typeof authRedirToDashboardExpiredResetTokenRouteImport
      parentRoute: typeof authRedirToDashboardRouteRoute
    }
    '/(auth)/_redir-to-dashboard/reset-password/$token': {
      id: '/(auth)/_redir-to-dashboard/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof authRedirToDashboardResetPasswordTokenRouteImport
      parentRoute: typeof authRedirToDashboardRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface authRedirToDashboardRouteRouteChildren {
  authRedirToDashboardExpiredResetTokenRoute: typeof authRedirToDashboardExpiredResetTokenRoute
  authRedirToDashboardForgotPasswordRoute: typeof authRedirToDashboardForgotPasswordRoute
  authRedirToDashboardInvalidResetTokenRoute: typeof authRedirToDashboardInvalidResetTokenRoute
  authRedirToDashboardLoginRoute: typeof authRedirToDashboardLoginRoute
  authRedirToDashboardSignupRoute: typeof authRedirToDashboardSignupRoute
  authRedirToDashboardResetPasswordTokenRoute: typeof authRedirToDashboardResetPasswordTokenRoute
}

const authRedirToDashboardRouteRouteChildren: authRedirToDashboardRouteRouteChildren =
  {
    authRedirToDashboardExpiredResetTokenRoute:
      authRedirToDashboardExpiredResetTokenRoute,
    authRedirToDashboardForgotPasswordRoute:
      authRedirToDashboardForgotPasswordRoute,
    authRedirToDashboardInvalidResetTokenRoute:
      authRedirToDashboardInvalidResetTokenRoute,
    authRedirToDashboardLoginRoute: authRedirToDashboardLoginRoute,
    authRedirToDashboardSignupRoute: authRedirToDashboardSignupRoute,
    authRedirToDashboardResetPasswordTokenRoute:
      authRedirToDashboardResetPasswordTokenRoute,
  }

const authRedirToDashboardRouteRouteWithChildren =
  authRedirToDashboardRouteRoute._addFileChildren(
    authRedirToDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  authRedirToDashboardRouteRoute: authRedirToDashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
